/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mapeo_proyecto_integrador;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author nana2
 */
public class LoginFrom extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrom.class.getName());

    /**
     * Creates new form LoginFrom
     */
    public LoginFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        jLabelRounded1 = new com.mycompany.mapeo_proyecto_integrador.JLabelRounded();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setBackground(new java.awt.Color(110, 125, 78));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(216, 224, 199));
        cancel.setText("Cancelar >");
        cancel.setBorder(null);
        cancel.addActionListener(this::cancelActionPerformed);
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 30));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(110, 125, 78));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Crear una Cuenta");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 340, 40));

        name.setBackground(new java.awt.Color(204, 204, 204));
        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setBorder(null);
        name.addActionListener(this::nameActionPerformed);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 200, 30));

        mail.setBackground(new java.awt.Color(204, 204, 204));
        mail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mail.setBorder(null);
        mail.addActionListener(this::mailActionPerformed);
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 210, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel2.setText("  Nombre :");
        jLabel2.setMaximumSize(new java.awt.Dimension(48, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(48, 14));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(48, 14));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setText("  Correo : ");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel4.setText("  Contraseña :");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 30));

        role.setBackground(new java.awt.Color(204, 204, 204));
        role.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Usuario", "Administrativo", "Analista", "Operador" }));
        role.setBorder(null);
        role.setOpaque(true);
        role.addActionListener(this::roleActionPerformed);
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, 30));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel5.setText("  Rol :");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 40, 30));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        password.setBorder(null);
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 190, 30));

        register.setBackground(new java.awt.Color(110, 125, 78));
        register.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Registrar");
        register.setPreferredSize(new java.awt.Dimension(84, 27));
        register.addActionListener(this::registerActionPerformed);
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 100, 30));

        jLabelRounded1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 340, 380));

        jLabel6.setBackground(new java.awt.Color(110, 125, 78));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        SessionFrom registration = new SessionFrom();
        registration.setVisible(true);
        registration.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        mail.requestFocusInWindow();
    }//GEN-LAST:event_nameActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
        role.requestFocusInWindow();

    }//GEN-LAST:event_mailActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
        password.requestFocusInWindow();
    }//GEN-LAST:event_roleActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

     
    String nom = name.getText().trim();
    String cor = mail.getText().trim();
    String cont = password.getText().trim();

    if (nom.isEmpty() && cor.isEmpty() && cont.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Los campos están vacíos", "MapTre - Error", 0);
        return;
    }
    if (nom.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El campo Nombre está vacío", "MapTre - Error", 2);
        return;
    }
    if (cor.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El campo Correo está vacío", "MapTre - Error", 2);
        return;
    }
    if (cont.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El campo Contraseña está vacío", "MapTre - Error", 2);
        return;
    }
    LocalDate fechaActual = LocalDate.now();
    String fecha = fechaActual.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

    String ro = role.getSelectedItem().toString();
    Query.registrarUsuario(nom, cor, cont, ro, fecha);
    
    javax.swing.JOptionPane.showMessageDialog(this, "           Bienvenido a Map tre "
        + "\nEsta es una aplicación sobre mapeo digital, "
        + "\nesperemos disfrutes la experiencia");
    SessionFrom inicio = new SessionFrom();
    inicio.setLocationRelativeTo(null);
    inicio.setVisible(true);
        
    this.dispose();   
    }//GEN-LAST:event_registerActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        register.doClick();
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.mycompany.mapeo_proyecto_integrador.JLabelRounded jLabelRounded1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton register;
    private javax.swing.JComboBox<String> role;
    // End of variables declaration//GEN-END:variables
}
