/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mapeo_proyecto_integrador;

import javax.swing.SwingUtilities;

/**
 *
 * @author nana2
 */
public class SessionFrom extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SessionFrom.class.getName());

    /**
     * Creates new form SessionFrom
     */
    public SessionFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        get = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        goout = new javax.swing.JButton();
        jLabelRounded1 = new com.mycompany.mapeo_proyecto_integrador.JLabelRounded();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 125, 78));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 340, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("  Correo :");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("  Contraseña :");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, 30));

        mail.setBackground(new java.awt.Color(204, 204, 204));
        mail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mail.setBorder(null);
        mail.addActionListener(this::mailActionPerformed);
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 190, 30));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        password.setBorder(null);
        password.setOpaque(true);
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, 30));

        get.setBackground(new java.awt.Color(110, 125, 78));
        get.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        get.setForeground(new java.awt.Color(255, 255, 255));
        get.setText("Ingresar");
        get.addActionListener(this::getActionPerformed);
        getContentPane().add(get, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 100, 30));

        jLabel4.setText("¿No tienes una cuenta?");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 150, 20));

        create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        create.setForeground(new java.awt.Color(110, 125, 78));
        create.setText("Crear Cuenta");
        create.setBorderPainted(false);
        create.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        create.addActionListener(this::createActionPerformed);
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 110, 20));

        goout.setBackground(new java.awt.Color(110, 125, 78));
        goout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        goout.setForeground(new java.awt.Color(216, 224, 199));
        goout.setText("Salir >");
        goout.setBorder(null);
        goout.addActionListener(this::gooutActionPerformed);
        getContentPane().add(goout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 80, 30));

        jLabelRounded1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 340, 380));

        fondo.setBackground(new java.awt.Color(110, 125, 78));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
       String cor = mail.getText().trim();
    String con = new String(password.getPassword()).trim();

    if (cor.isEmpty() && con.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Los campos están vacíos", "Error de entrada", 0);
        return;
    }
    if (cor.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "El campo Correo está vacío", "Error de entrada", 2);
        return;
    }
    if (con.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "El campo Contraseña está vacío", "Error de entrada", 2);
        return;
    }

    if (Query.validarLogin(cor, con)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido al sistema!");
        this.dispose();
        SwingUtilities.invokeLater(() -> {
        new mapa().setVisible(true);
        });
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos", "Error", 0);
        password.setText("");
    }
    }//GEN-LAST:event_getActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        LoginFrom registro = new LoginFrom();
        registro.setLocationRelativeTo(null);
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createActionPerformed

    private void gooutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gooutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_gooutActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
        password.requestFocusInWindow();
    }//GEN-LAST:event_mailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        get.doClick();
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton get;
    private javax.swing.JButton goout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.mycompany.mapeo_proyecto_integrador.JLabelRounded jLabelRounded1;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
